[build]
  base = "apps/experiment-06"
  publish = ".next/standalone/apps/experiment-06"
  command = "pnpm build"
  environment = { NODE_VERSION = "18.17.1" }  # Changed to exact version

[[redirects]]
  from = "/_next/static/*"
  to = "/_next/static/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200